### ISSUE TITLE
 Could not import package using Unity 2020.3.14f1 Personal

### ISSUE THREAD

**Issue by grandpa3d** [SrejonKhan/AnotherFileBrowser#2]
Here are the errors I received when trying to import to Unity 2020.3.14f1 Personal.

1) Assembly 'Library/ScriptAssemblies/Unity.PlasticSCM.Editor.dll' will not be loaded due to errors:
Reference has errors 'unityplastic'.

2) Assembly 'Packages/com.unity.collab-proxy/Lib/Editor/PlasticSCM/unityplastic.dll' will not be loaded due to errors:
unityplastic references strong named System.Windows.Forms Assembly references: 4.0.0.0 Found in project: 2.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

**Comment by SrejonKhan** [comment]
Hello, 

This is happening for version mismatching of System.Windows.Forms dll. 

The easiest solution is to untick **Assembly Version Validation** from Player Settings. 
![image](https://user-images.githubusercontent.com/57011529/130949491-2433cc62-ee14-4a68-98c0-33b63e3ae3c6.png)
Although, it will prone to some risk factors in the future. As disabling this validation means any Assembly won't check reference version anymore. So, in some cases, it may cause unexpected behaviour. 

Or, another solution is to delete the existing System.Windows.Forms dll from `Plugins/AnotherFileBrowser/Plugins` folder and import v4.0 dll from `C:\Windows\Microsoft.NET\Framework\v4.0.x` folder. Which I've not tested in build. 

Please let me know if you're still facing the issues.

**Comment by grandpa3d** [comment]
All it required was a program restart. Seems there is an issue with Unitys PlasticSCM. It appears that several packages have been causing this error to appear. Most have been resolved with a restart of the program.

**Comment by SrejonKhan** [comment]
Glad to hear that, there is a easy fix. Thanks for sharing.

**Comment by digichowkdeveloper** [comment]
Assembly 'Library/ScriptAssemblies/Unity.CollabProxy.Editor.dll' will not be loaded due to errors:
Reference has errors 'Unity.PlasticSCM.Editor'.

**Comment by digichowkdeveloper** [comment]
>) 
Here are the errors when I update my unity collab package to Plastic SCM.

Assembly 'Library/ScriptAssemblies/Unity.CollabProxy.Editor.dll' will not be loaded due to errors:
Reference has errors 'Unity.PlasticSCM.Editor'.

Assembly 'Library/ScriptAssemblies/Unity.PlasticSCM.Editor.dll' will not be loaded due to errors:
Reference has errors 'unityplastic'.

Assembly 'Packages/com.unity.collab-proxy/Lib/Editor/PlasticSCM/log4netPlastic.dll' will not be loaded due to errors:
log4net references strong named System.Configuration Assembly references: 2.0.0.0 Found in project: 4.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

Assembly 'Packages/com.unity.collab-proxy/Lib/Editor/PlasticSCM/unityplastic.dll' will not be loaded due to errors:
unityplastic references strong named System.Windows.Forms Assembly references: 4.0.0.0 Found in project: 2.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

>) And When I uncheck  Assembly Version Validation from Player Settings, the plastic icon is visible but it shows me impersonate token error.

Thanks
